name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  push_to_registry:
      name: Push Docker image to Docker Hub
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@4.1.1
    
        - name: Login do Docker
          uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d
          with:
            username: ${{ secrets.USER }}
            password: ${{ secrets.PASSWORD }}
            
        - name: Docker Metadata action
          id: meta
          uses: docker/metadata-action@31cebacef4805868f9ce9a0cb03ee36c32df2ac4
          with:
            images: mochoa_coder-docker-extension-desktop-extension_coder_data   
        - name: Build and push Docker image
          uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
          with:
            context: .
            file: ./Dockerfile
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}
